### ISSUE TITLE
Storage Intensive packages are being uploaded to github

### ISSUE THREAD

**Issue by sugamkarki** [sarthakdhakal/ECommerce_ASP.NET#1]
As you can see that all the packages are kept in your ```packages``` folder and are being pulled from there. But Some of these packages are quite heavy when pulling/pushing from/to Github. So, what you have to do is create a ```package.json``` file and specify all your dependencies in there.

You can specify the path of the packages in your ```project.json``` if you wish for a smoother transaction of the modules. 

What you are doing is downright stupid and barbaric, and you are frankly being inconsiderate of the good hospitality of Github and.

Hope to see it updated

``` Thank you 😀 ```

**Comment by sarthakdhakal** [comment]
I am glad that you have specified this issue and helped me optimize my project. I will be implementing the solution that you have specified. I hope you will help me in the future finding such issues in my project. 

As I am a beginner and gaining an understanding of properly developing the project. I hope you will suggest me ways to  develop my project in the best optimized way,

Thanks for the help.

**Comment by sarthakdhakal** [comment]
I have closed this issue for the time being.
